# Banner, Ports and Protocols
import pyfiglet

banner = pyfiglet.figlet_format("PORT SCANNER")


ports_dict = {
              "7": "ECHO",
              "21": "FTP",
              "22": "SSH",
              "23": "TELNET",
              "25": "SMTP",
              "80": "HTTP",
              "443": "HTTPS",
              "53": "DNS",
              "67": "DHCP",
              "68": "DHCP",
              "69": "TFTP",
              "88": "KERBEROS",
              "110": "POP3",
              "119": "Network News Transfer Protocol (NNTP)",
              "123": "Network Time Protocol (NTP)",
              "137": "NETBIOS-ns",
              "139": "NETBIOS-ssn",
              "143": "Internet Message Access Protocol (IMAP)",
              "161": "Simple Network Management Protocol (SNMP)",
              "445": "Server Message Block (SMB)",
              "1701": "Layer 2 Tunneling Protocol (L2TP)",
              "1723": "Point-to-Point Tunneling Protocol (PPTP)",
              "873": "Remote synchronization (Rsync)",
              "902": "VMware",
              "993": "IMAP SECURE",
              "1025": "MICROSOFT RPC",
              "1080": "SOCKS",
              "1194": "OpenVPN",
              "1337": "WASTE",
              "1589": "Cisco VLAN Query Protocol (VQP)",
              "1725": "STEAM",
              "2049": "Network File System (NFS)",
              "2483": "ORACLE DB",
              "2484": "ORACLE DB",
              "3074": "XBOX LIVE",
              "5432": "PostgreSQL",
              "3306": "MySQL Database",
              "3389": "Remote Desktop Protocol (RDC)",
              "194": "Internet Relay Chat (IRC)",
              "6665": "Internet Relay Chat",
              "6666": "Internet Relay Chat",
              "6667": "Internet Relay Chat",
              "6668": "Internet Relay Chat",
              "6669": "Internet Relay Chat",
              "6999": "BitTorrent",
              "1521": "Oracle Database",
              "49153": "Windows RPC (Remote Procedure Call)",
              "5353": "mDNS (Multicast Domain Name System)",
              "5900": "Virtual Network Computing (VNC)",
              "5355": "LLMNR (Link-Local Multicast Name Resolution)",
              "27017": "MongoDB Database"
              }
